### PR TITLE
Remove empty .NET Core projects

### PR DESCRIPTION
**Pull request by Siliconrob**
Update target C# language to latest
Update to Visual Studio 2017 project format
Use ThreadPool to start a background thread and pass thread token as cancellation condition on notification loop

This came up because of Issues brought up and trying to remedy some of the issues

### CODE REVIEW

**Comment by Siliconrob** [comment]
❓  OK ❓

I'm on a roll now and can make some changes into this project if you want.

**Comment by dyatchenko** [comment]
Was there any reason for removing Core projects and compiling it for the latest version? Old C# language was intentionally used to give people opportunity to use the tool for many-years-old legacy projects (we actually had a complaint that some stuff doesn't work because of modern C# syntax). The right thing to do here would be to make the tool asynchronous (using async/await) and push it to NuGet. But it would be better to leave old implementation for people who is not really up-to-date with modern technologies.

**Comment by Siliconrob** [comment]
For the .NET Core project they were empty so I wasn't sure what you wanted to do there.  I deleted the folders until there were going to be filled in.

I can see you want to keep the old syntax for legacy projects.  If you want to go async/await then that is ok, but I was not sure if you wanted to go all in because once one thing is async it percolates across everything.

I would like to do the async/await adoption, but then how do you want to do it.  Add async duplicate methods in the same file i.e. 

Start()
StartAsync()

**Comment by dyatchenko** [comment]
.NET Core projects weren't empty - there were links to the source .cs files. So the same files were used in two projects - like you can compile it for .NET and for .NET Core (Cross-platform). What about Async/Await I would create a separate project for now or push current stuff to NuGet with version 1 and then make async changes and push it to NuGet again with version 2, so people will be able to pick whatever version they want (any version would work).

**Comment by dyatchenko** [comment]
I will create a NuGet project and push current stuff there this weekend.

**Comment by Siliconrob** [comment]
I like this project so I need your guidance.  Will wait for you to make the changes or set the stage for what to do.

**Comment by asulwer** [comment]
forked and created a pull request with conversion to Task and async/await.  for backwards compatibility these can still be used synchronously, you will get a warning if you do.

**Pull request closed without merging**
