### PR TITLE
.NET Core Port

### PR DESCRIPTION
**Pull request by Siliconrob**
Copied code to separate folders and appended .Core to the folders along with separate .NET Core solution.

Thread.Abort is removed from .NET Core, using a cancellation token instead.

Unit Tests don't work exactly the same so made a console program that cycles through the tests.

Added my simple console application that monitors a single table and writes results to console ServiceBrokerListener.TableListener.Core.  Have a .NET 4.6.1 version of this as well which I used to test and compare results.

### CODE REVIEW

**Comment by Siliconrob** [comment]
Adjustments?

**Comment by dyatchenko** [comment]
That's a good stuff. Thanks for developing. Sorry for the delay - didn't have laptop with me. Let me please take a look at the code before merging.

Thanks,
Dmitrii

**Comment by Siliconrob** [comment]
Thank you

**Comment by dyatchenko** [comment]
OK. I checked the code - there were some missed references and some temporary files were included. This stuff was fixed and the projects start from scratch without any issues for now (on my machine at least). Could you please check how it works for you?

Thanks,
Dmitrii

**Comment by Siliconrob** [comment]
I think it works, but I am having trouble running the project as it is all .NET 1.6 and it appears I don't have that for some reason.  Made a small minor change to test project as separate pull request.

Looks like you did a lot of merge work so thanks, but .NET Core is such a mess to work with now kind of hate it.

**Pull request merged**
